build:
    nodes:
        coverage:
            tests:
                override:
                    - command: php-scrutinizer-run
                    -
                        command: php vendor/bin/phpunit --coverage-clover coverage/clover.xml
                        coverage:
                            file: coverage/clover.xml
                            format: clover
            environment:
                php:
                    version: 7.4
