language: php

os: linux

# ubuntu 16.04
dist: xenial

php:
  - 7.1
  - 7.2

jobs:
  include:
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: LINTER_RUN=run COVERAGE_RUN=run
    - php: nightly
  fast_finish: true

git:
    depth: 1

cache:
  directories:
    # speed
    - $HOME/.composer/cache/files

before_script:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - if [ "$LINTER_RUN" = "run" ]; then make lint ; fi;
  - if [ "$LINTER_RUN" = "run" ]; then composer phpstan ; fi;
  - if [ "$COVERAGE_RUN" = "run" ]; then composer phpunit-with-coverage ; fi;
  - if [ "$COVERAGE_RUN" != "run" ]; then composer phpunit ; fi;
